language: java
sudo: false
jdk:
  - openjdk11
cache:
  directories:
    - '$HOME/.m2/repository'
install: true
script:
  - mvn clean verify site -Dmaven.test.skip=true -Dcompile.boot.classpath=$(jdk_switcher home openjdk8)/jre/lib/rt.jar
  - jdk_switcher use openjdk8
  - mvn test -Dmaven.main.skip
before_deploy:
  - JAVA_HOME=$($HOME/openjdk11) mvn deploy -Dmaven.test.skip=true -Dmaven.main.skip -Dmaven.install.skip=true -DaltDeploymentRepository=travis::default::file:target/deploy
deploy:
  provider: bintray
  file: target/descriptor.json
  user: fbacchella
  skip_cleanup: true
  on: release
  key:
    secure: joBFFpOZrd8k6lRKSENJrQsGUPAbD51NblgmILHUIRpOR5IE3E7l7PlHTJjN86NnK41n+PuZ0BusbzzETcKMCbeCmcnwRBSTJrq+JJIiNsYDin1nUEPZLk+A6hBdL8m0feA+nTiwoG7F8BlllQdySVI5YFrpQrPuX+65XdYkOfhee8NuMhT8uqPkmQ2LwvsHN2Plvx/LyxslXZ8zxdb9+8Iaq4NtYHTW5R6dIbhYSV++QeKPd9L1uatN5+0pCyqJxd5Wk/UhmQC0q8oGwa03e461GPsYcmriLsGitmvdUE1gy4nbSsoh15LNTtbo9vE0zzrqXNxr+IizTwtKJHGiyHAPtJWG9wG6Jgtp30BK23S7f1umIi+ZinZxdj/K2ItheO0J0xJIEVzmsUqzcq2A/6lOtC3rzxsAILQpzIWi6jbA/GGZc9ILO9wTYs5Js4UHKLbNZU2s09DD04JSIYjHDJ8BSokNE7pXVqbU12pUjCWBesSRAJEHj0Xp54utvlqSJZwBVuEbx6WF3vbe6eiI9mmKGuP4iZr7zVU5RjOcD9oH840chjyDMqhaNqj8L2e1BgcQMH53f5jLW8IazSaJAe1jwCXT5EtbO1nNLNFpvV+p4gb/k2JOige8/keVRnC5lKSYMHI3wZhG8DB2WcyNTg1WrXDsY5YmACG4oHsIcgQ=
notifications:
  irc:
    - irc.freenode.org#jrds
